services:
  bot:
    container_name: discord-voice-notify-bot-js-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/botuser/app:cached
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    tty: true
    command: sleep infinity
